### ISSUE TITLE
#1: Web UI 'sid' issue from spamming commands

### ISSUE THREAD

**Issue by cheesiang-vaultex** [exberry-io/Issue-Tracking#2]
There was a small error with the sid because of repeated spamming of commands (in this case, alternating between 'active orders', 'orders history' & 'trades history'. Might be a bug or simply just overwhelming the system. But the end result is that the data doesn't load or will take a very long time to do so. 
![image](https://user-images.githubusercontent.com/109207109/178681747-f2d42a1d-660d-4f5e-ab60-508ca65f00a8.png)
![image](https://user-images.githubusercontent.com/109207109/178681884-41df7222-0e48-4e3e-b645-d9fab5ae929c.png)

Though, I sometimes do encounter sid error on the Trading API side in the sandbox.

**Comment by dudikrisher** [comment]
Fixed

**Comment by denispalii** [comment]
The fix was applied on master, it will be deployed on UAT on the next release.
cc @dudikrisher
