### ISSUE TITLE
#2: Instrument details are obstructed on mobile UI

### ISSUE THREAD

**Issue by cheesiang-vaultex** [exberry-io/Issue-Tracking#3]
When viewing details, some of the instrument names can't be seen as the details too long for a small box. Perhaps we can make the box auto fit according to the instrument details?

![image](https://user-images.githubusercontent.com/109207109/178682421-382e224d-a096-499b-a30c-b154a32f7362.png)

**Comment by dudikrisher** [comment]
Fixed
