### ISSUE TITLE
#3: Fill or Kill Order with insufficient balance

### ISSUE THREAD

**Issue by cheesiang-vaultex** [exberry-io/Issue-Tracking#4]
![image](https://user-images.githubusercontent.com/109207109/179173300-f9862285-c344-4f58-a486-542d15ff0601.png)

This is a Fill or Kill market order of 222 gold which **won’t be fulfilled** because of 2 reasons:
1) Not enough market buy orders for 222 gold 
2) Trader doesn’t have 222 gold to sell. 

But shouldn’t there be an error from the pre-clearing module first, saying that there isn’t enough gold? (error 105: insufficient balance) This is a not really a problem since this order can’t be fulfilled either way. From my impression, the pre-clearing module is supposed to kick in before checking if the order can even be fulfilled. 

This test might imply that the sequence of programming logic is:   
1) Check if order can be fulfilled first. If no, kill the order.
2) Then check if trader has necessary balance for order. If no, reject the order and error pops up.

![image](https://user-images.githubusercontent.com/109207109/179179255-829efb65-d1ea-4232-8a18-24dd1f71bd7f.png)

I've also placed an order without indicating a valid instrument, but I received a successful acknowledge response (sig = 1) without an error response.

**Comment by dudikrisher** [comment]
All errors are returned on `orders` stream, if you will subscribe to it prior of sending the order you will see the relevant error .
You are right, balance is being checked before sending the order to the matching engine to be executed.

**Comment by dudikrisher** [comment]
not a bug
