### ISSUE TITLE
#4 Mobile UI Loading

### ISSUE THREAD

**Issue by cheesiang-vaultex** [exberry-io/Issue-Tracking#5]
This is a small issue for the user experience on the mobile UI (Android). 
After logging in, the page would be half cropped out. Thus, affecting the user experience when using through mobile. 
But this issue is resolved, simply by reloading the page. If possible, fixing this issue without needing to refresh the page, would optimise the user experience.

Before Refreshing page:
![image](https://user-images.githubusercontent.com/109207109/181674556-0327c8b5-8807-49e0-b26d-88df443c6ce3.png)

After Refreshing page:
![image](https://user-images.githubusercontent.com/109207109/181674615-9507e303-6db0-403d-80e1-ed7bc54175e9.png)

**Comment by denispalii** [comment]
Hi @cheesiang-vaultex, could you please specify some details like android version, phone model and browser?

**Comment by cheesiang-vaultex** [comment]
Hi @denispalii, I used a 

Phone Model: Huawei P30 Pro (VOG-L29)
Android Version: Android 10
Browser: Chrome

**Comment by denispalii** [comment]
Thanks @cheesiang-vaultex , I'll come with an update

**Comment by cheesiang-vaultex** [comment]
Hi @denispalii, can I also add that the cancel active order feature on the Mobile UI is missing unlike the Web UI Version, which is supposed to be located on the right hand side. 

Web UI:
![image](https://user-images.githubusercontent.com/109207109/182790614-788a11c6-a46f-4bda-9040-566ead0632f8.png)


Mobile UI:
![image](https://user-images.githubusercontent.com/109207109/182790495-2f477567-7bcc-4d53-b5df-d85befa2f27f.png)

**Comment by denispalii** [comment]
The fix will be applied on the next release, thank you for reporting it
cc @cheesiang-vaultex
