### ISSUE TITLE
#5 Opting into Calendar Auctions in Admin API

### ISSUE THREAD

**Issue by cheesiang-vaultex** [exberry-io/Issue-Tracking#6]
![Screenshot (33)](https://user-images.githubusercontent.com/109207109/182754848-13a97ceb-5d35-41a8-825d-f02f5e7d7499.png)

Hi Team, in the instruments set up on the exchange side of the Admin API, I think there is a slight mistake in the logic. As seen above, the instrument doesn't subscribe to "Calendar Auctions", however as seen below, we are able to configure the "Auctions Set-up". 

![Screenshot (32)](https://user-images.githubusercontent.com/109207109/182755045-e9d81bb6-8463-481c-b333-89ec8dd50107.png)

On the contrary, when we do subscribe to the "Calendar Auctions", the option for "Auctions Set-up" is missing.

![Screenshot (34)](https://user-images.githubusercontent.com/109207109/182755274-bd11feb1-da77-435c-a1ae-c42f0de79765.png)

![Screenshot (35)](https://user-images.githubusercontent.com/109207109/182755285-82265d45-6626-4b96-a503-2c66de5b47c2.png)

**Comment by VictoriaBordian** [comment]
The auction can be configured as a part of a calendar or of an instrument:
    1. When "Calendar Auctions" is enabled, the instrument will use the auctions that belongs to the associated calendar  (no "Auctions Set-up" option is displayed in the menu for this instrument, as even if the instrument has their own auctions, it will use the calendars auctions)
    2. When "Calendar Auctions" is disabled, "Auctions Set-up" option is displayed in the menu, meaning you can set-up auctions that will work on this specific instrument only, regardless the auctions of the associated calendar.
