### ISSUE TITLE
#6: Missing transactions on the Algorand Ledger ("None" for Instrument settings)

### ISSUE THREAD

**Issue by cheesiang-vaultex** [exberry-io/Issue-Tracking#7]
To give some context, the instrument is "DUR-BER". This instrument pair's settings are "None", so it's not "Fully Collateralized Internally" and has "External & Internal" Trade Flows. Because of this, I was able to execute trades that I did not have enough assets for. 
![image](https://user-images.githubusercontent.com/109207109/182781324-a0873683-5066-4d34-aead-e23d0e1cbc2f.png)

The main issue is, when I reference to Algorand, there are no records of such transactions taking place. Whereas on the Trading API and UI, there are records of these executed trades. If this is by design, then there is no issue since the exchange is always going to be "Fully Collateralized Internally". Otherwise, this could prove to be an issue in the future and become something to investigate. 

On the Asset side on Algorand:
![Screenshot (39)](https://user-images.githubusercontent.com/109207109/182782155-e132adf6-e04e-4962-a29f-3c4dc583872a.png)

On my Account side on Algorand:
![Screenshot (40)](https://user-images.githubusercontent.com/109207109/182782318-6b55a5d1-7778-4ada-aaf5-012d89369f52.png)

Trading API Records:
![image](https://user-images.githubusercontent.com/109207109/182782766-97dff706-17c8-4d61-aef1-3495f00beb27.png)

Admin API Records (broker side):
![image](https://user-images.githubusercontent.com/109207109/184278545-951a40a3-871d-42d1-ae72-257cf72d6e4a.png)

**Comment by VictoriaBordian** [comment]
The tradeFlow of the "DUR-BER" instrument is "None", that’s why no trades transactions are captured in the ledger.

**Comment by cheesiang-vaultex** [comment]
We will test whether this will be an issue when the ERP platform is integrated into the Exberry platform.
