### ISSUE TITLE
#7 In Light Mode on UI, Vaultex Logo can't be seen

### ISSUE THREAD

**Issue by cheesiang-vaultex** [exberry-io/Issue-Tracking#8]
This is a small issue, but in light mode, the "Vaultex" logo cannot be seen as the words "Vaultex" is in white at the top left. Below is the comparison between light and dark mode on the Web & Mobile UI.

**Web:**
Dark Mode
![image](https://user-images.githubusercontent.com/109207109/184283089-00e52a48-3174-4e0d-aebf-650308d5b32a.png)

Light Mode
![image](https://user-images.githubusercontent.com/109207109/184283079-cfd4ffbc-b08c-4dbe-85ba-8ef6276e518a.png)

**Mobile:**
Dark Mode
![image](https://user-images.githubusercontent.com/109207109/184283119-4fdee2a0-b042-4d8a-b3bc-cfb6b55f5737.png)

Light Mode
![image](https://user-images.githubusercontent.com/109207109/184283130-23eb45af-38b5-4bb5-bcca-becf78bb6d46.png)

**Comment by dudikrisher** [comment]
FIXED
